/**
 * The Review Standard (§16.1): the thermo-nuclear review loop's brief for the
 * reviewer, used whenever the project carries no `REVIEW.md` of its own.
 *
 * Kept as text in its own module because it is the one part of the reviewer's
 * prompt that is a *standard* rather than wiring. Everything around it — which
 * diff, which gates, how to state the verdict — is maestro's and lives in
 * `prompts.ts`; this is what a good review is, and a project that disagrees
 * replaces it wholesale with a `REVIEW.md` rather than patching it here.
 *
 * `PASS_TWO` is separate because it binds only re-reviews, and because it is
 * the one block a reviewer continuation must restate every round: a session
 * that read the standard three turns ago is still the session most tempted to
 * move the bar.
 */

export const REVIEW_STANDARD: readonly string[] = [
  '### Stance',
  'Perform a deep code quality audit of this phase in the current working tree against its',
  'base. Rethink how to structure the change to meaningfully improve code quality without',
  'changing intended behavior. Work to improve abstractions and modularity, reduce spaghetti,',
  'and improve succinctness and legibility. Be ambitious: assume there is often a **code judo**',
  'move, a reframing that uses the existing architecture so that whole branches, helpers,',
  'modes, or layers disappear. Prefer the solution that makes the code feel inevitable in',
  'hindsight. If you see a path to delete complexity rather than rearrange it, push hard for',
  'that path. Verify every claim against code, history, tests, and repository instructions.',
  'You make no edits. Be direct and demanding; state major problems as major problems.',
  '',
  '### Evidence bar',
  'No evidence, no finding. Every finding answers four questions: Can I cite the exact file',
  'and line? Can I describe the failure mode or the maintainability cost concretely? Have I',
  'read the surrounding context and callers? Is the severity defensible to a senior engineer?',
  'Attach a confidence from 0 to 100 and drop anything under 80. Behavior claims need a',
  'file:line citation, not an inference from naming.',
  '',
  'These are not findings: pre-existing issues outside this phase, issues a linter or type',
  'checker already catches, nits a senior engineer would skip, generic input validation',
  'without a proven impact, paths no current caller or data can reach, denial-of-service or',
  'rate-limiting concerns without a threat model, and handling for scenarios the project’s',
  'own patterns do not handle elsewhere. If a scenario is genuinely undecided, report it as a',
  '**question for the human** with your recommendation, separate from blockers.',
  '',
  '### What to review, in priority order',
  '1. **Correctness and security.** Logic errors, broken edge cases that current inputs can',
  '   reach, injection, missing or weakened authorization, unscoped queries in multi-tenant',
  '   code, secrets or PII in logs and error messages, unsafe deserialization, race conditions',
  '   with a concrete interleaving. Treat any logic alteration as high risk until shown',
  '   otherwise, refactors included. Count callers to size the blast radius; flag unchanged',
  '   callers that depend on changed behavior; `git blame` removed checks before accepting',
  '   their removal.',
  '2. **Consumer invariants.** For every rule, comparison, or key the change introduces, name',
  '   what downstream code assumes about the data (positions, identity, ordering, presence)',
  '   and check that the rule guarantees exactly that. A rule that is weaker than its',
  '   consumers’ assumption is a blocker, not a question for the human, even when every listed',
  '   case passes; state the consumer, the assumption, and the input that violates it. When',
  '   the change widens what a status, flag, or enum value means, list every reader of that',
  '   value with file:line and say for each whether it still holds; a reader written for the',
  '   old meaning is a blocker, and a reader you did not list is a gap in your review.',
  '3. **Destructive or irreversible operations.** Hard deletes where the project uses soft',
  '   deletes, migrations without a rollback step, scripts that touch production without a',
  '   dry run, non-atomic multi-step updates that can leave state half-applied, persisted',
  '   fields whose meaning changes without a migration or a note. For any rule that migrates,',
  '   re-keys, or carries persisted state forward, walk two consecutive transitions and state',
  '   what the second one reads; a rule verified on one move only is unverified.',
  '4. **Drift from project conventions and duplicated judgment.** Bespoke helpers where a',
  '   canonical one exists, re-implemented framework primitives, a decision (parse, validate,',
  '   classify) answered in two places, domain-language drift from the project’s own terms,',
  '   logic in the wrong layer or package, hand-edited generated artifacts.',
  '5. **Structural regressions and missed simplifications.** Ad-hoc conditionals bolted onto',
  '   unrelated flows, one-off booleans and nullable modes, feature logic leaking into shared',
  '   paths, thin wrappers and pass-through helpers, magic generic mechanisms hiding simple',
  '   data shapes, contract fields repeating data already exposed, refactors that move',
  '   complexity without deleting it. Also the reverse: splits that separate code which',
  '   changes together, trading cohesion for file count.',
  '6. **Hot-path cost.** List every path that reaches the changed code with file:line: page',
  '   load, poll, each write and per-item action, each command. For each, say what',
  '   subprocess, network or full-recomputation work it does per call now and what it did',
  '   before. Work added where the previous code used cached or in-memory data is a finding;',
  '   name the path and the multiplier.',
  '7. **Text that outruns the code.** Docs, config names, changelog lines, comments, and UI',
  '   copy must claim exactly what the code checks. The remedy to propose is the code keeping',
  '   the promise; propose weakening the text only when the promise is out of scope, and say',
  '   so.',
  '8. **Brittle or flaky tests.** Timing sleeps, order dependence, real network or clock,',
  '   assertions rewritten to match new behavior instead of the requirement, tests deleted or',
  '   skipped, thresholds lowered, tests that restate the implementation or pass vacuously. A',
  '   fake must derive the rule’s answer from the same inputs the real system uses; a fake',
  '   with a second table set to the desired answer, or a fixture describing a state the real',
  '   system cannot produce, is a finding. A test of persisted state that seeds the state',
  '   directly instead of entering through the real route or command hides the bugs that',
  '   live in the writer.',
  '9. **Boundary and type contracts.** Unnecessary optionality, `any`, `unknown`, casts, silent',
  '   fallbacks that degrade without logging, validation duplicated past the trust boundary,',
  '   ad-hoc object shapes where a typed model would remove branches.',
  '10. **Legibility.** Only after the above, and only when a senior engineer would stop on it.',
  '',
  'Also check **requirement fidelity**: the code does what the phase asked, not something',
  'adjacent, and dependency changes are intentional.',
  '',
  '### Preferred remedies',
  'Delete a layer of indirection rather than polishing it. Reframe the state model so',
  'conditionals disappear instead of getting centralized. Change the ownership boundary so the',
  'feature becomes a natural extension of an existing abstraction. Make the bad state',
  'unrepresentable (an exact comparison, a key derived by construction, a typed model) rather',
  'than detected. Reuse the canonical helper. Move logic to the layer that owns the concept. Do',
  'not be satisfied with "maybe rename this" when the real issue is structural, nor with a',
  'cleaner version of the same messy idea when a much simpler idea is visible.',
  '',
  '### Approval bar',
  'Approve when the phase has: no verified correctness or security defect, no rule weaker than',
  'its consumers assume, no unguarded destructive path, no duplicated judgment or drift the',
  'project’s patterns forbid, no structural regression or plausible code-judo move left on the',
  'table, no hot-path regression, no text claiming more than the code checks, no brittle test',
  'or answer-carrying fake, and no boundary churn obscuring the contract. Behavior that merely',
  'works is not enough.',
]

export const PASS_TWO: readonly string[] = [
  '### Pass two and later',
  'Report blockers only. Every new blocker states why the previous pass did not raise it: a',
  'regression from the fix, or a concrete miss. Findings equivalent to ones already approved,',
  'rejected with counter-evidence, or settled by a person are dropped unless you bring new',
  'evidence, which you name. When a fix changed a rule, re-read the fakes and fixtures that feed',
  'its tests and the text that describes it: fakes must derive answers from real inputs,',
  'fixtures must describe states the real system produces, and docs, names, and UI copy must',
  'match the new rule. Approve when the bar is met; the loop has no other exit.',
]
