#!/usr/bin/env bash
# Provision a runnable git worktree for {{PROJECT_NAME}}.
#
# implement-plan runs this as `commands.worktree_prepare`, with the
# VINTA_WORKTREE_* environment set. You can also run it by hand:
#
#   {{SCRIPT_DIR}}/prepare.sh <worktree-name> [--dry-run]
#
# --dry-run (or VINTA_WORKTREE_DRY_RUN=1) prints every command instead of
# running it, and writes nothing.
#
# What it guarantees (the commands.worktree_prepare contract):
#   - a worktree at $VINTA_WORKTREE_PATH, on the new branch
#     $VINTA_WORKTREE_BRANCH, based on $VINTA_WORKTREE_BASE_REF;
#   - runnable on its own: dependencies, env files, databases and compose
#     project are the worktree's, never shared writable state with main;
#   - a non-zero exit on any failure, and never a write to main's tracked files;
#   - running again for the same name works once teardown.sh has run.
#
# Generated by the vinta-ai-workflows bootstrap. This project owns it now: edit
# the PROJECT STEPS regions freely, and keep teardown.sh in step with them.
set -euo pipefail
. "$(cd "$(dirname "$0")" && pwd)/lib.sh" "$@"

# ---------------------------------------------------------------------------
# What this worktree got. The PROJECT STEPS below set these; the summary at the
# end records them so teardown and implement-plan's lane reset can read them.
# ---------------------------------------------------------------------------
DEPS_STRATEGY=copy        # copy | reinstall
DEPS_PATHS=""             # space-separated, relative to the worktree
ENV_STRATEGY=copy         # copy | symlink
ENV_FILES=""
DEV_DB_ENGINE=""          # postgres | mysql | sqlite | mongo | redis; empty = no dev DB
DEV_DB_STRATEGY=fork      # fork | share | stub
DEV_DB_FORKED=""
DEV_DB_URL_VAR=""
DEV_DB_RESET=""           # command that returns the dev DB to a fresh state
TEST_DB_ENGINE=""         # empty = no test DB
TEST_DB_STRATEGY=fork     # fork | share
TEST_DB_FORKED=""
TEST_DB_URL_VAR=""
TEST_DB_RESET=""
USES_COMPOSE=0            # 1 when the project runs services through docker compose
COMPOSE_NETWORK=per-worktree
SHARED_VOLUMES=""         # compose volume keys safe to share: read-only caches, never data
REDIS_DB_INDEX=""
S3_PREFIX=""
CRON_DISABLED=false
NOTES=""

created_worktree=0
on_exit() {
  local status=$?
  [ "$status" -eq 0 ] && return 0
  [ "$DRY_RUN" = 1 ] && return 0
  log "provisioning failed (exit $status)"
  if [ "$created_worktree" = 1 ]; then
    log "removing the half-made worktree at $WT_PATH"
    git -C "$MAIN" worktree remove --force "$WT_PATH" >/dev/null 2>&1 || true
    git -C "$MAIN" branch -D "$BRANCH" >/dev/null 2>&1 || true
  fi
  log "databases or volumes created before the failure are removed by teardown.sh, run with the same VINTA_WORKTREE_* environment"
}
trap on_exit EXIT

# ---------------------------------------------------------------------------
# 1. Sanity
# ---------------------------------------------------------------------------
if git -C "$MAIN" worktree list --porcelain | grep -Fxq "worktree $WT_PATH"; then
  echo "a worktree is already registered at $WT_PATH; run teardown.sh first" >&2
  exit 1
fi
if [ -e "$WT_PATH" ]; then
  echo "$WT_PATH already exists and is not a registered worktree; move it aside first" >&2
  exit 1
fi
if git -C "$MAIN" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "branch $BRANCH already exists; pick another name or delete it" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. Create the worktree
# ---------------------------------------------------------------------------
log "creating $WT_PATH on $BRANCH from $BASE_REF"
case "$BASE_REF" in
  origin/*) run git -C "$MAIN" fetch --quiet origin || log "fetch failed; using the local $BASE_REF" ;;
esac
run mkdir -p "$(dirname "$WT_PATH")"
run git -C "$MAIN" worktree add --quiet -b "$BRANCH" "$WT_PATH" "$BASE_REF"
created_worktree=1

# ---------------------------------------------------------------------------
# 3. PROJECT STEPS. Each region is filled in for this project at generation
#    time. Write only inside "$WT_PATH", to databases named by
#    `forked_db_name`, or under the summary dir. Use `run` for every command so
#    --dry-run stays honest.
# ---------------------------------------------------------------------------

# >>> deps: every dependency dir is the worktree's own; never a symlink to main.
#   clone_dir node_modules            # copy-on-write; also each workspace member's
#   (cd "$WT_PATH" && run uv sync)    # virtualenvs always reinstall
#   DEPS_PATHS="node_modules"
# <<< deps

# >>> env: copy env files (compose isolation below appends to .env, so it must
#   be a copy), then point their connection strings at this worktree's state.
#   copy_file .env
#   ENV_FILES=".env"
# <<< env

# >>> dev_db: fork the local dev database (or leave DEV_DB_ENGINE empty).
#   require_local_url "$main_database_url"
#   DEV_DB_FORKED="$(forked_db_name app_dev)"
#   run createdb -T app_dev "$DEV_DB_FORKED"
#   set_env .env DATABASE_URL "postgres://localhost:5432/$DEV_DB_FORKED"
#   DEV_DB_ENGINE=postgres DEV_DB_URL_VAR=DATABASE_URL
#   DEV_DB_RESET="dropdb --if-exists $DEV_DB_FORKED && createdb -T app_dev $DEV_DB_FORKED"
# <<< dev_db

# >>> test_db: give the test runner its own database name.
#   TEST_DB_FORKED="$(forked_db_name app_test)"
#   set_env .env TEST_DATABASE_URL "postgres://localhost:5432/$TEST_DB_FORKED"
#   TEST_DB_ENGINE=postgres TEST_DB_URL_VAR=TEST_DATABASE_URL
#   TEST_DB_RESET="dropdb --if-exists $TEST_DB_FORKED"
# <<< test_db

# >>> compose: set USES_COMPOSE=1 when the project runs services through
#   docker compose. Step 4 then isolates the stack generically.
#   USES_COMPOSE=1
#   SHARED_VOLUMES=""
# <<< compose

# >>> other: Redis index / key prefix, S3 prefix, queue and index suffixes,
#   cron off, migrations against the forked DB.
#   S3_PREFIX="wt-$NAME/"; set_env .env S3_PREFIX "$S3_PREFIX"
#   (cd "$WT_PATH" && run python manage.py migrate)
# <<< other

# ---------------------------------------------------------------------------
# 4. Compose isolation. COMPOSE_PROJECT_NAME alone does not isolate external or
#    fixed-name volumes, or fixed host ports; the generated out-of-tree override
#    does. Never edit the project's tracked compose files.
# ---------------------------------------------------------------------------
FORKED_VOLUMES_YAML="[]"
PORTS_STRIPPED=""
BASE_COMPOSE_FILE=""
if [ "$USES_COMPOSE" = 1 ]; then
  run mkdir -p "$(dirname "$COMPOSE_OVERRIDE")"
  share_args=""
  for vol in $SHARED_VOLUMES; do share_args="$share_args --share-volume $vol"; done
  report="$(mktemp)"
  # shellcheck disable=SC2086  # share_args is a deliberate word list
  run "$SCRIPT_DIR/gen-compose-worktree-override.sh" --main "$MAIN" --worktree "$WT_PATH" \
    --name "$NAME" --out "$COMPOSE_OVERRIDE" $share_args 2> "$report" >/dev/null
  cat "$report" >&2
  for f in compose.yaml compose.yml docker-compose.yaml docker-compose.yml; do
    if [ -f "$MAIN/$f" ]; then BASE_COMPOSE_FILE="$f"; break; fi
  done
  set_env .env COMPOSE_PROJECT_NAME "$COMPOSE_PROJECT"
  set_env .env COMPOSE_FILE "$BASE_COMPOSE_FILE:$COMPOSE_OVERRIDE"
  case " $ENV_FILES " in *" .env "*) ;; *) ENV_FILES="$ENV_FILES .env" ;; esac
  # The generator reports "- <key> (<reason>) -> <volume>" per forked volume.
  FORKED_VOLUMES_YAML="$(sed -n 's/^    - \([^ ]*\) (\(.*\)) -> \(.*\)$/\1|\2|\3/p' "$report" | {
    out="" sep=""
    while IFS='|' read -r key reason pinned; do
      case "$reason" in external*) reason=external ;; *) reason=fixed-name ;; esac
      out="$out$sep{volume_key: $(yaml_str "$key"), reason: $reason, forked_name: $(yaml_str "$pinned")}"
      sep=", "
    done
    printf '[%s]' "$out"
  })"
  PORTS_STRIPPED="$(sed -n 's/^  stripped host-port publishing from: //p' "$report" | sed 's/^none$//; s/,//g')"
  rm -f "$report"
fi

# ---------------------------------------------------------------------------
# 5. Summary: read by teardown, by implement-plan's lane reset, and by
#    vinta-ai-maestro. Every key is present; null means none.
# ---------------------------------------------------------------------------
db_yaml() { # engine strategy forked url_var reset
  if [ -z "$1" ]; then printf 'null'; return 0; fi
  printf '\n    engine: %s\n    strategy: %s\n    forked_name: %s\n    connection_url_var: %s\n    reset_cmd: %s' \
    "$1" "$2" "$(yaml_str "$3")" "$(yaml_str "$4")" "$(yaml_str "$5")"
}

if [ "$USES_COMPOSE" = 1 ]; then
  compose_yaml="$(printf '\n    project_name: %s\n    network_strategy: %s\n    override_path: %s\n    base_compose_file: %s\n    forked_volumes: %s\n    shared_volumes: %s\n    ports_stripped_from: %s' \
    "$(yaml_str "$COMPOSE_PROJECT")" "$COMPOSE_NETWORK" "$(yaml_str "$COMPOSE_OVERRIDE")" \
    "$(yaml_str "$BASE_COMPOSE_FILE")" "$FORKED_VOLUMES_YAML" "$(yaml_list "$SHARED_VOLUMES")" \
    "$(yaml_list "$PORTS_STRIPPED")")"
else
  compose_yaml=null
fi

if [ "$DRY_RUN" = 1 ]; then
  log "dry run: would write the summary to $SUMMARY"
else
  mkdir -p "$(dirname "$SUMMARY")"
  cat > "$SUMMARY" <<EOF
# Written by $(basename "$0"); read by teardown.sh and implement-plan.
name: $(yaml_str "$NAME")
path: $(yaml_str "$WT_PATH")
branch: $(yaml_str "$BRANCH")
base_ref: $(yaml_str "$BASE_REF")
created_at: $(yaml_str "$(date -u +%Y-%m-%dT%H:%M:%SZ)")
plan_path: $(yaml_str "$PLAN_PATH")
flags:
  deps_change: true
  schema_change: true
  env_change: true
  test_infra_change: true
  compose_change: $([ "$USES_COMPOSE" = 1 ] && echo true || echo false)
state:
  deps:
    strategy: $DEPS_STRATEGY
    paths: $(yaml_list "$DEPS_PATHS")
  env:
    strategy: $ENV_STRATEGY
    files: $(yaml_list "$ENV_FILES")
  dev_db: $(db_yaml "$DEV_DB_ENGINE" "$DEV_DB_STRATEGY" "$DEV_DB_FORKED" "$DEV_DB_URL_VAR" "$DEV_DB_RESET")
  test_db: $(db_yaml "$TEST_DB_ENGINE" "$TEST_DB_STRATEGY" "$TEST_DB_FORKED" "$TEST_DB_URL_VAR" "$TEST_DB_RESET")
  compose: $compose_yaml
  other:
    redis_db_index: $(yaml_str "$REDIS_DB_INDEX")
    s3_prefix: $(yaml_str "$S3_PREFIX")
    cron_disabled: $CRON_DISABLED
  sandbox:
    tier: none
    launcher: null
    deny: []
    allow: []
notes: $(yaml_str "Provisioned by $(basename "$0") (kind: $KIND). $NOTES")
EOF
fi

# ---------------------------------------------------------------------------
# 6. Report (implement-plan quotes the tail of this)
# ---------------------------------------------------------------------------
cat <<EOF
worktree: $WT_PATH
branch:   $BRANCH (from $BASE_REF)
deps:     $DEPS_STRATEGY ${DEPS_PATHS:-(none)}
env:      $ENV_STRATEGY ${ENV_FILES:-(none)}
dev db:   ${DEV_DB_FORKED:-(none)}
test db:  ${TEST_DB_FORKED:-(none)}
compose:  $([ "$USES_COMPOSE" = 1 ] && echo "$COMPOSE_PROJECT" || echo "(not used)")
summary:  $SUMMARY
teardown: $SCRIPT_DIR/teardown.sh $NAME
EOF
