#!/usr/bin/env bash
# Remove a worktree prepare.sh made for {{PROJECT_NAME}}, and everything it
# created outside git.
#
# implement-plan runs this as `commands.worktree_teardown`, with the same
# VINTA_WORKTREE_* environment the worktree was provisioned with. You can also
# run it by hand:
#
#   {{SCRIPT_DIR}}/teardown.sh <worktree-name> [--dry-run] [--force]
#
# Safe to run more than once: every step skips what is already gone. It refuses
# a worktree with uncommitted changes unless --force (or VINTA_WORKTREE_FORCE=1)
# is given, and only drops databases named `*_wt_<worktree>`. It never runs
# `docker compose down -v`, which would also delete volumes shared with main.
#
# Generated by the vinta-ai-workflows bootstrap. Keep the PROJECT STEPS regions
# in step with prepare.sh's.
set -euo pipefail
. "$(cd "$(dirname "$0")" && pwd)/lib.sh" "$@"

registered=0
if git -C "$MAIN" worktree list --porcelain | grep -Fxq "worktree $WT_PATH"; then
  registered=1
fi

# ---------------------------------------------------------------------------
# 1. Refuse to lose work
# ---------------------------------------------------------------------------
if [ "$registered" = 1 ] && [ "$FORCE" != 1 ]; then
  if [ -n "$(git -C "$WT_PATH" status --porcelain)" ]; then
    echo "$WT_PATH has uncommitted changes; commit or stash them, or pass --force to discard them" >&2
    exit 1
  fi
fi

# ---------------------------------------------------------------------------
# 2. PROJECT STEPS, in reverse order of prepare.sh. Each must tolerate state
#    that is already gone.
# ---------------------------------------------------------------------------

# >>> other: undo what prepare.sh's "other" region created outside the worktree.
# <<< other

# >>> test_db: drop the forked test database.
#   db="$(forked_db_name app_test)"; require_forked_name "$db"
#   run dropdb --if-exists "$db"
# <<< test_db

# >>> dev_db: drop the forked dev database.
#   db="$(forked_db_name app_dev)"; require_forked_name "$db"
#   run dropdb --if-exists "$db"
# <<< dev_db

# ---------------------------------------------------------------------------
# 3. Compose: stop the stack, then remove only the volumes the override pinned
#    for this worktree. Shared volumes stay.
# ---------------------------------------------------------------------------
if [ -f "$COMPOSE_OVERRIDE" ]; then
  if [ "$registered" = 1 ] && command -v docker >/dev/null 2>&1; then
    (cd "$WT_PATH" && run docker compose -p "$COMPOSE_PROJECT" down) || log "compose down failed; continuing"
  fi
  # The override's volumes: block lists each pinned name; that is the manifest.
  for vol in $(sed -n '/^volumes:/,/^[^ ]/s/^    name: "\(.*\)"$/\1/p' "$COMPOSE_OVERRIDE"); do
    case "$vol" in
      *_wt_"$NAME"_*) run docker volume rm "$vol" >/dev/null 2>&1 || log "volume $vol already gone" ;;
      *) log "skip volume $vol: not named for this worktree" ;;
    esac
  done
  run rm -f "$COMPOSE_OVERRIDE"
fi

# ---------------------------------------------------------------------------
# 4. The worktree and its branch
# ---------------------------------------------------------------------------
if [ "$registered" = 1 ]; then
  if [ "$FORCE" = 1 ]; then
    run git -C "$MAIN" worktree remove --force "$WT_PATH"
  else
    run git -C "$MAIN" worktree remove "$WT_PATH"
  fi
else
  log "no worktree registered at $WT_PATH"
fi
# The branch goes only when it holds no commits of its own (its tip is already
# in the base ref, or merged into main's HEAD). Anything else is kept.
if git -C "$MAIN" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  if git -C "$MAIN" merge-base --is-ancestor "$BRANCH" "$BASE_REF" 2>/dev/null \
    || git -C "$MAIN" merge-base --is-ancestor "$BRANCH" HEAD 2>/dev/null; then
    run git -C "$MAIN" branch -D "$BRANCH" >/dev/null
  else
    log "kept branch $BRANCH: it has commits not in $BASE_REF (delete it with git branch -D once you are sure)"
  fi
fi

run rm -f "$SUMMARY"
log "done"
